---
title: "Joins, strings, and dates"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(kableExtra)
```

### Part 1: Data wrangling refresher

```{r}
my_penguins <- penguins %>% 
  filter(island %in% c("Biscoe","Dream")) %>%
  select(-year, -sex) %>%
  mutate(body_mass_kg = body_mass_g / 1000) %>%
  rename(location = island)
  
```

### Part 2: Joins

```{r}
animals <- tibble::tribble(
             ~location,   ~species,  ~maturity,
              "lagoon",   "bobcat",    "adult",
               "bluff",   "coyote", "juvenile",
               "creek",      "fox",    "adult",
                "oaks", "squirrel", "juvenile",
               "bluff",   "bobcat",    "adult"
             )
sites <- tibble::tribble(
           ~location,      ~full_site_name, ~jurisdiction,
             "beach",       "Goleta Beach",     "SB City",
            "lagoon",        "UCSB Lagoon",        "UCSB",
             "bluff",       "Ellwood Mesa",     "SB City",
              "oaks", "Fremont Campground",        "USFS"
           )

```

#### Full Join

```{r}
full_join_example <- full_join(animals, sites, by = "location") 
```

#### Left Join

```{r}
left_join_example <- left_join(animals, sites, by = "location") 
```

#### Inner Join

```{r}
inner_join_example <- inner_join(animals, sites, by = "location")
```

Joining when key variables have non-matching names

```{r}
sites_2 <- sites %>%
  rename(loc = location)
nonmatch_example <- full_join(animals, sites_2, by = c("location" = "loc"))
```

#### Semi Join

```{r}
semi_join_example <- semi_join(animals, sites, by = "location")
```

#### Anti Join

```{r}
anti_join_example <- anti_join(animals, sites, by = "location")
```

### Dates and times with `lubridate` 

```{r}
my_date <- "03-15-1998"

lubridate::mdy(my_date)

my_date <- "11/7/2003" 

lubridate::dmy(my_date)

my_date <- "08-Jun-1974"

lubridate::dmy(my_date)

my_date <- "19610518"

lubridate::ymd(my_date)
```

```{r}
lubridate::ymd("1942-08-30")

lubridate::mdy("09/22/84")

lubridate::mdy("1/1/69")
```

```{r}
time <- "2020-08-12 11:18"

time <- ymd_hm(time)
```

```{r}
# returns time for different time zone
with_tz(time, "America/Los_Angeles")

with_tz(time,"America/New_York")

with_tz(time, "America/Anchorage")

with_tz(time, "America/Denver")

my_time <- ymd_hms(time)

year(my_time)

day(my_time)

month(my_time)

hour(my_time)

minute(my_time)

second(my_time)
```

```{r}
my_birthday <- lubridate::ymd_hm("20000519 12:01")

wday(my_birthday, label = TRUE)

week(my_birthday)
```
